server:
  port: 7982

spring:
  application:
    name: producer
  cloud:
    nacos:
      discovery:
        server‐addr: 39.107.93.94:8848
        namespace: c7297287-2583-478f-8ec3-6fcaaad3a294

rocketmq:
#  name-server: 118.190.244.217:9876
  name-server: 39.107.93.94:9876
#  nameServer: 127.0.0.1:9876
    #  extNameServer: 127.0.0.1:9876
  producer:
    send-message-timeout: 300000
    group: rocketmq-group

