server:
  port: 9000

spring:
  application:
    name: gateway

    gateway:
      discovery:
        locator:
          #让gateway通过服务发现组件找到其他的微服务
          enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: 39.107.93.94:8848
        namespace: c7297287-2583-478f-8ec3-6fcaaad3a294
      gateway:
        route:
          config:
            group: DEFAULT_GROUP
            data-id: gateway-router
